# Generated by Django 4.2.7 on 2024-01-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_adminstrateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
