# Generated by Django 4.2.7 on 2024-01-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_categorie_voyage_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='categorie',
        ),
    ]
