# Generated by Django 4.2.7 on 2024-01-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_voyage_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.categorie'),
            preserve_default=False,
        ),
    ]
