# Generated by Django 4.2.7 on 2024-01-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_voyage_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='nbr_places',
            field=models.IntegerField(),
        ),
    ]
