# Generated by Django 4.2.7 on 2024-01-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_voyage_nbr_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_voyage',
            name='amountPaid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client_voyage',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
