# Generated by Django 4.2.7 on 2024-01-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol',
            name='nbr_places',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vol',
            name='classe',
            field=models.CharField(choices=[('eco', 'economie'), ('bsn', 'bisness')], max_length=100),
        ),
    ]
