# Generated by Django 4.2.7 on 2024-01-06 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_vol_nbr_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='vol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vol'),
            preserve_default=False,
        ),
    ]
