# Generated by Django 4.2.7 on 2024-01-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_voyage_vol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='vol',
        ),
    ]
