# Generated by Django 4.2.7 on 2024-01-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_vol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol',
            name='titre',
            field=models.CharField(default='titre1', max_length=100),
        ),
    ]
