# Generated by Django 4.2.7 on 2024-02-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_hotel_voyage_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='categorie_image',
            field=models.ImageField(blank=True, default='voyagepic.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(blank=True, default='hotel.jpeg', null=True, upload_to=''),
        ),
    ]
