# Generated by Django 4.2 on 2024-02-06 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='CIN',
        ),
        migrations.RemoveField(
            model_name='client',
            name='solde',
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nbr_etoiles',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')]),
        ),
    ]
