# Generated by Django 4.2 on 2024-02-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_remove_client_cin_remove_client_solde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
